#!/usr/bin/env python3
import argparse
import subprocess
from pathlib import Path


TEXT_TYPES = set("TtWw")


def parse_args():
    parser = argparse.ArgumentParser(description="Generate a SIMA debug symbol table C source.")
    parser.add_argument("--nm", default="nm")
    parser.add_argument("--elf", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    return parser.parse_args()


def collect_symbols(nm, elf):
    result = subprocess.run(
        [nm, "-n", "--defined-only", str(elf)],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    symbols = []
    seen = set()
    text_start = None
    text_end = None
    for line in result.stdout.splitlines():
        fields = line.split(None, 2)
        if len(fields) != 3:
            continue
        addr, kind, name = fields
        if kind not in TEXT_TYPES or name.startswith("$"):
            continue
        value = int(addr, 16)
        if name == "_text_start":
            text_start = value
        elif name == "_text_end":
            text_end = value
        key = (value, name)
        if key in seen:
            continue
        seen.add(key)
        symbols.append((value, name))
    symbols.sort(key=lambda item: (item[0], item[1]))
    if text_start is None:
        text_start = symbols[0][0] if symbols else 0
    if text_end is None:
        text_end = (symbols[-1][0] + 1) if symbols else 0
    return symbols, text_start, text_end


def c_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def write_source(path, symbols, text_start, text_end):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as out:
        out.write("/* Auto-generated by scripts/gen_symtab.py. */\n")
        out.write("#include <types.h>\n")
        out.write("#include <debug/symbol.h>\n\n")
        out.write("const struct dbg_symbol dbg_symbol_table[] = {\n")
        for addr, name in symbols:
            out.write(f'\t{{ 0x{addr:016x}UL, "{c_escape(name)}" }},\n')
        out.write("};\n\n")
        out.write(f"const uint32_t dbg_symbol_count = {len(symbols)}U;\n")
        out.write(f"const uint64_t dbg_symbol_text_start = 0x{text_start:016x}UL;\n")
        out.write(f"const uint64_t dbg_symbol_text_end = 0x{text_end:016x}UL;\n")


def main():
    args = parse_args()
    symbols, text_start, text_end = collect_symbols(args.nm, args.elf)
    write_source(args.out, symbols, text_start, text_end)


if __name__ == "__main__":
    main()
