/*
 * Copyright (C) 2026 Hustler Lo.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ARM64_QEMU_PLATFORM_QEMU_H
#define ARM64_QEMU_PLATFORM_QEMU_H

#define CONFIG_STATIC_ARM64_PLATFORM	1
#define CONFIG_STATIC_QEMU_PLATFORM	1

#define CONFIG_BOARD			qemu
#define CONFIG_SCENARIO			qemu
#define CONFIG_GUEST_KERNEL_RAWIMAGE	1
#define CONFIG_HAS_HSM			0
#define CONFIG_AUTOSTART_VM		1
#define CONFIG_LAUNCH_VMS_FROM_BSP	1
#define CONFIG_STATIC_VFDT		1
#define CONFIG_HV_RAM_START		0x50000000UL
#define CONFIG_STACK_SIZE		8192U
#define CONFIG_SCHED_IORR		y
#define CONFIG_SERIAL_8250_PCI		0
#define CONFIG_CONSOLE_DEFAULT_VM	ACRN_INVALID_VMID
#define CONFIG_CONSOLE_LOGLEVEL_DEFAULT	6U
#define CONFIG_MEM_LOGLEVEL_DEFAULT	0U
#define CONFIG_NPK_LOGLEVEL_DEFAULT	0U
#define CONFIG_VUART_TIMER_PCPU		BSP_CPU_ID
#define CONFIG_VUART_RX_BUF_SIZE	256U
#define CONFIG_VUART_TX_BUF_SIZE	256U
#define CONFIG_VM_CONSOLE_RINGBUF_VM_NUM (PRE_VM_NUM + SERVICE_VM_NUM)
#define CONFIG_VM_CONSOLE_RINGBUF_SIZE	4096U
#define CONFIG_MAX_EMULATED_MMIO_REGIONS 8U
#define CONFIG_MAX_MSIX_TABLE_NUM	16U
#define CONFIG_MAX_PCI_DEV_NUM		16U
#define CONFIG_MAX_PT_IRQ_ENTRIES	0U
#define CONFIG_MAX_IOAPIC_NUM		0U
#define CONFIG_SPACE_SIZE		0x10000000UL
#define CONFIG_ADDR			0xcf8U
#define CONFIG_DATA			0xcfcU
#define CONFIG_IGD_SBDF			0U

#define MAX_PCPU_NUM			8U
#define PRE_VM_NUM			2U
#define SERVICE_VM_NUM			1U
#define MAX_POST_VM_NUM			0U
#define MAX_TRUSTY_VM_NUM		0U
#define MAX_VUART_NUM_PER_VM		2U

#define RTVM_SEVERITY_LEVEL		0x30U

#define QEMU_VIRT_RAM_START		0x40000000UL
#define QEMU_VIRT_RAM_SIZE		0x40000000UL

#define QEMU_VIRT_LOW_MMIO_START	0x00000000UL
#define QEMU_VIRT_LOW_MMIO_SIZE		0x10000000UL
#define QEMU_VIRT_PL011_BASE		0x09000000UL
#define QEMU_VIRT_GICD_BASE		0x08000000UL
#define QEMU_VIRT_GICD_SIZE		0x00010000UL
#define QEMU_VIRT_GICR_BASE		0x080A0000UL
#define QEMU_VIRT_GICR_STRIDE		0x00020000UL
#define QEMU_VIRT_GICR_SIZE		(MAX_PCPU_NUM * QEMU_VIRT_GICR_STRIDE)
#define QEMU_VIRT_GIC_MMIO_START	QEMU_VIRT_GICD_BASE
#define QEMU_VIRT_GIC_MMIO_END		QEMU_VIRT_PL011_BASE
#define QEMU_VIRT_GIC_IIDR		0x43bU

#define QEMU_VIRT_PCIE_MMIO_START	0x10000000UL
#define QEMU_VIRT_PCIE_MMIO_SIZE	0x30000000UL

#endif /* ARM64_QEMU_PLATFORM_QEMU_H */
