/*
 * Copyright (C) 2026 Intel Corporation.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ARM64_QEMU_CONFIG_H
#define ARM64_QEMU_CONFIG_H

#define CONFIG_BOARD			qemu
#define CONFIG_SCENARIO			qemu
#define CONFIG_GUEST_KERNEL_RAWIMAGE	1
#define CONFIG_HAS_HSM			0
#define CONFIG_AUTOSTART_VM		1
#define CONFIG_LAUNCH_VMS_FROM_BSP	1
#define CONFIG_STATIC_VFDT		1
#define CONFIG_HV_RAM_START		0x50000000UL
#define CONFIG_STACK_SIZE		8192U
#define CONFIG_SCHED_IORR		y
#define CONFIG_SERIAL_8250_PCI		0
#define CONFIG_CONSOLE_DEFAULT_VM	ACRN_INVALID_VMID
#define CONFIG_CONSOLE_LOGLEVEL_DEFAULT	6U
#define CONFIG_MEM_LOGLEVEL_DEFAULT	0U
#define CONFIG_NPK_LOGLEVEL_DEFAULT	0U
#define CONFIG_VUART_TIMER_PCPU		BSP_CPU_ID
#define CONFIG_VUART_RX_BUF_SIZE	256U
#define CONFIG_VUART_TX_BUF_SIZE	256U
#define CONFIG_VM_CONSOLE_RINGBUF_VM_NUM (PRE_VM_NUM + SERVICE_VM_NUM)
#define CONFIG_VM_CONSOLE_RINGBUF_SIZE	4096U
#define CONFIG_MAX_EMULATED_MMIO_REGIONS 8U
#define CONFIG_MAX_MSIX_TABLE_NUM	16U
#define CONFIG_MAX_PCI_DEV_NUM		16U
#define CONFIG_MAX_PT_IRQ_ENTRIES	0U
#define CONFIG_MAX_IOAPIC_NUM		0U
#define CONFIG_SPACE_SIZE		0x10000000UL
#define CONFIG_ADDR			0xcf8U
#define CONFIG_DATA			0xcfcU
#define CONFIG_IGD_SBDF			0U

#define MAX_PCPU_NUM			8U
#define PRE_VM_NUM			1U
#define SERVICE_VM_NUM			1U
#define MAX_POST_VM_NUM			0U
#define MAX_TRUSTY_VM_NUM		0U
#define MAX_VUART_NUM_PER_VM		2U

#define RTVM_SEVERITY_LEVEL		0x30U

#endif /* ARM64_QEMU_CONFIG_H */
